import { Context } from '../types/context';
// Importe todas as funções administrativas aqui (mesmas do adminCallbackRouter)
// Para simplificar, listamos apenas os nomes e os callbacks; a implementação real
// pode ser feita no adminCallbackRouter ou adaptada para usar este mapa.

export const adminCallbackMap: Record<string, (ctx: Context, data?: string) => Promise<any>> = {
  // Dashboard e menus
  'admin_dashboard': (ctx) => import('./adminMenu').then(m => m.showAdminDashboard(ctx)),
  'admin_menu_config': (ctx) => import('./adminMenu').then(m => m.showConfigMenu(ctx)),
  'admin_menu_actions': (ctx) => import('./adminMenu').then(m => m.showActionsMenu(ctx)),
  'admin_menu_transactions': (ctx) => import('./adminMenu').then(m => m.showTransactionsMenu(ctx)),
  'admin_menu_updates': (ctx) => import('./adminMenu').then(m => m.showUpdatesMenu(ctx)),

  // Segurança (novos)
  'security_menu': (ctx) => import('./securityConfig').then(m => m.showSecurityConfig(ctx)),
  'security_toggle_2fa': (ctx) => import('./securityConfig').then(m => m.toggle2FA(ctx)),
  'security_toggle_device': (ctx) => import('./securityConfig').then(m => m.toggleDeviceSecurity(ctx)),
  'security_toggle_strict': (ctx) => import('./securityConfig').then(m => m.toggleStrictDevice(ctx)),
  'security_set_attempts': (ctx) => import('./securityConfig').then(m => m.setMaxPasswordAttempts(ctx)),
  'security_set_block': (ctx) => import('./securityConfig').then(m => m.setBlockDuration(ctx)),
};

// Lista de todos os callbacks registrados (para revisão)
export const allAdminCallbacks = [
  'admin_dashboard',
  'admin_menu_config',
  'admin_menu_actions',
  'admin_menu_transactions',
  'admin_menu_updates',
  'admin_config_general',
  'config_support',
  'config_separator',
  'config_logdest',
  'config_maintenance',
  'config_restart',
  'admin_config_admins',
  'admin_add_adm',
  'admin_remove_adm',
  'admin_config_affiliates',
  'aff_toggle_system',
  'aff_set_points',
  'aff_set_min',
  'aff_set_multiplier',
  'admin_config_users',
  'admin_config_pix',
  'pixcfg_toggle_mode',
  'pixcfg_set_key',
  'pixcfg_toggle_qr',
  'pixcfg_toggle_copy',
  'pixcfg_set_expiration',
  'pixcfg_set_min',
  'pixcfg_set_max',
  'pixcfg_edit_message',
  'admin_config_logins',
  'logins_add',
  'logins_remove',
  'logins_remove_platform',
  'logins_zero',
  'logins_detailed',
  'logins_change_price',
  'logins_change_all_price',
  'admin_config_search',
  'research_add_image',
  'research_remove_image',
  'admin_actions_messages',
  'template_view_',
  'template_edit_text_',
  'template_edit_image_',
  'template_reset_',
  'admin_actions_buttons',
  'btnlist_',
  'btnadd_',
  'btnedit_',
  'btnremove_',
  'btnreorder_',
  'btnreset_',
  'admin_actions_broadcast',
  'bcast_all',
  'bcast_active',
  'bcast_buyers',
  'bcast_affiliates',
  'bcast_btn_comprar',
  'bcast_btn_saldo',
  'bcast_btn_cadastrar',
  'bcast_btn_suporte',
  'bcast_btn_link',
  'bcast_send',
  'bcast_cancel',
  'antiflood_menu',
  'antiflood_set_',
  'wa_af_menu',
  'wa_af_set_',
  'admin_actions_antiflood',
  'admin_actions_notifications',
  'notif_toggle_',
  'admin_transactions_withdrawals',
  'saque_view_',
  'saque_aprovar_',
  'saque_rejeitar_',
  'saque_reprocessar_',
  'admin_transactions_pix_manual',
  'pixmanual_view_',
  'pixmanual_confirm_',
  'pixmanual_reject_',
  'admin_transactions_stats',
  'stats_refresh',
  'promo_settings',
  'promo_set_autodelete',
  'promo_set_viewers',
  'admin_inactivity',
  'inactivity_set_days',
  'admin_transcription',
  'transcription_set_key',
  'giftcard_admin_menu',
  'giftcard_admin_create',
  'giftcard_admin_batch',
  'giftcard_admin_list',
  'giftcard_admin_view_',
  'giftcard_admin_disable_',
  'giftcard_admin_delete_',
  'admin_updates_check',
  'admin_updates_logs',
  'admin_updates_clean',
  // Segurança
  'security_menu',
  'security_toggle_2fa',
  'security_toggle_device',
  'security_toggle_strict',
  'security_set_attempts',
  'security_set_block',
];
